### DISCUSSION TITLE
width 깨짐 에러 발생

### DISCUSSION THREAD

**Discussion by lindist12** [codestates/siphoon-note#114] [Q&A]
```js
export const Card = ({ diary }) => {
  const navigator = useNavigate();
  const [hover, setHover] = useState(true);
  const deletehandle = () => {
    navigator('/signin');
  };
  // console.log(diary);
  // const createdAt =
  //   diary.createdAt.slice(0, 10) + ' ' + diary.createdAt.slice(11, 19);
  return (
    <div>
      {hover ? (
        <div>
          <CardContainer className="front">
            <Title>{diary.id}번째 글쓰기</Title>
            <Content>{diary.content}</Content>
            <MdOutlineFlipCameraAndroid
              className="bb"
              onMouseEnter={() => setHover(false)}
            />
          </CardContainer>
          <Backs className="back" position="absolute" margintop="-100px">
            <span className="createdat">{diary.createdAt}</span>
            <span className="cus">
              <RiPencilLine className="cu" />
              수정
              <RiDeleteBin6Line className="cu" onClick={deletehandle} />
              삭제
            </span>
          </Backs>
        </div>
      ) : (
        <div>
          <CardContainer
            className="front"
            rotate="rotateY(-180deg)"
            position="absolute"
          >
            <Title>{diary.id}번째 글쓰기</Title>
            <Content>{diary.content}</Content>
            <MdOutlineFlipCameraAndroid className="bb" />
          </CardContainer>
          <Backs
            className="back"
            rotate="rotateY(0deg)"
            position="static"
            onMouseLeave={() => setHover(true)}
          >
            <span className="createdat">{diary.createdAt}</span>
            <span className="cus">
              <RiPencilLine className="cu" />
              수정
              <RiDeleteBin6Line className="cu" onClick={deletehandle} />
              삭제
            </span>
          </Backs>
        </div>
      )}
    </div>
  );
};
```

===================================== style

```css
import styled from 'styled-components';




export const Wrapper1 = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1.8rem;
  // max-width: 340px;
  .cc {
    position: relative;
  }
  .cu {
    cursor: pointer;
    width: 30px;
    bottom: 100px;
    border: 1px solid blue;
    margin: 3px;
  }
`;
export const Wrapper2 = styled(Wrapper1)``;
export const Wrapper3 = styled(Wrapper1)``;

export const CardContainer = styled.div`
  border: 3px solid black;
  background: white;
  border-radius: 20px;
  max-height: 281px;
  gap: 20px;
  overflow: hidden;
  flex-wrap: wrap;
  font-size: 1.2rem;
  padding: 1rem;
  box-shadow: 8px 8px 5px rgb(0, 0, 0, 0.2);
  position: ${props => props.position || 'static'};
  transition: 3s;
  transform: ${props => props.rotate || 'rotateY(0deg)'};
  backface-visibility: hidden;
  .bb {
    position: absolute;
    top: 0;
    right: 0;
    border: 1px solid blue;
    width: 30px;
    height: 30px;
  }
  background-color: ${props => props.bg || 'white'};
`;

export const Backs = styled.div`
  display: block;
  border: 3px solid black;
  background: white;
  border-radius: 20px;
  max-height: 281px;
  // height: ${props => props.height || '0px'};
  gap: '20px';
  overflow: hidden;
  flex-wrap: wrap;
  font-size: 1.2rem;
  padding: 1rem;
  box-shadow: 8px 8px 5px rgb(0, 0, 0, 0.2);
  margin-top: ${props => props.margintop || '0px'};
  transition: 3s;
  backface-visibility: hidden;
  position: ${props => props.position || 'static'};
  transform: ${props => props.rotate || 'rotateY(-180deg)'};

  .createdat {
    display: block;
    text-align: right;
  }
  background-color: ${props => props.bg || 'gray'};
`;


```
